{{- if .Values.secret.create -}}


apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secret.name | default (include "theia.fullname" .) }}
  labels:
    {{- include "theia.labels" . | nindent 4 }}
type: Opaque
data:
{{- range $key, $val := .Values.secret.data }}
  {{ $key }}: {{ $val | b64enc }}
{{- end }}
{{- end -}}
